package view;


import view.TicketsReport;
import view.addCustomer;
import view.addFlight;
import view.displayCustomers;
import view.searchCustomer;
import view.tickets;
import view.userForm;


//https://www.youtube.com/watch?v=7xmUxhLslxg&list=PLuji25yj7oIJ1L8s-DF9TDRIOEDzqo72A&index=2
/**
 *
 * @author IT MODERN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        AddCustomer = new javax.swing.JMenu();
        addCustomer = new javax.swing.JMenuItem();
        searchmenubtn = new javax.swing.JMenuItem();
        displayCustomertb = new javax.swing.JMenuItem();
        ticketsreport = new javax.swing.JMenu();
        Bocktickets = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addflightbtn = new javax.swing.JMenuItem();
        userform = new javax.swing.JMenu();
        userCreation = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        AddCustomer.setText("Customer");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });

        addCustomer.setText("Add Customer");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });
        AddCustomer.add(addCustomer);

        searchmenubtn.setText("Search Customer");
        searchmenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchmenubtnActionPerformed(evt);
            }
        });
        AddCustomer.add(searchmenubtn);

        displayCustomertb.setText("Display Customer");
        displayCustomertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCustomertbActionPerformed(evt);
            }
        });
        AddCustomer.add(displayCustomertb);

        jMenuBar1.add(AddCustomer);

        ticketsreport.setText("Tickets");

        Bocktickets.setText("Book Tickets");
        Bocktickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BockticketsActionPerformed(evt);
            }
        });
        ticketsreport.add(Bocktickets);

        jMenuItem1.setText("Tickets Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ticketsreport.add(jMenuItem1);

        jMenuBar1.add(ticketsreport);

        jMenu3.setText("Flights");

        addflightbtn.setText("Add Flight");
        addflightbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addflightbtnActionPerformed(evt);
            }
        });
        jMenu3.add(addflightbtn);

        jMenuBar1.add(jMenu3);

        userform.setText("Users");

        userCreation.setText("UserCreation");
        userCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCreationActionPerformed(evt);
            }
        });
        userform.add(userCreation);

        jMenuBar1.add(userform);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
       // addCustomer custo= new addCustomer();
        //jDesktopPane1.add(custo);
        //custo.setVisible(true);
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        // TODO add your handling code here:
        addCustomer custo= new addCustomer();
        jDesktopPane1.add(custo);
        custo.setVisible(true);
    }//GEN-LAST:event_addCustomerActionPerformed

    private void searchmenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchmenubtnActionPerformed
        searchCustomer search= new searchCustomer();
          jDesktopPane1.add(search);
          search.setVisible(true);
    }//GEN-LAST:event_searchmenubtnActionPerformed

    private void displayCustomertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCustomertbActionPerformed
        displayCustomers diplcus= new displayCustomers();
        jDesktopPane1.add(diplcus);
        diplcus.setVisible(true);
    }//GEN-LAST:event_displayCustomertbActionPerformed

    private void addflightbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addflightbtnActionPerformed
        addFlight flight= new addFlight();
        jDesktopPane1.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_addflightbtnActionPerformed

    private void BockticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BockticketsActionPerformed
         
        tickets bock= new tickets();
        jDesktopPane1.add(bock);
        bock.setVisible(true);
    }//GEN-LAST:event_BockticketsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        TicketsReport report= new TicketsReport();
        jDesktopPane1.add(report);
        report.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void userCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCreationActionPerformed
       
             userForm user= new userForm();
        jDesktopPane1.add(user);
        user.setVisible(true);
        
        
    }//GEN-LAST:event_userCreationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddCustomer;
    private javax.swing.JMenuItem Bocktickets;
    private javax.swing.JMenuItem addCustomer;
    private javax.swing.JMenuItem addflightbtn;
    private javax.swing.JMenuItem displayCustomertb;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem searchmenubtn;
    private javax.swing.JMenu ticketsreport;
    private javax.swing.JMenuItem userCreation;
    private javax.swing.JMenu userform;
    // End of variables declaration//GEN-END:variables
}
